[package]
name = "chem_3d_builder_rs"
version = "0.4.0"
edition = "2024"

[dependencies]
chembuider-rs = { git = "https://github.com/IndigoCarmine/chembuider-rs" }
moleucle_3dview_rs = { git = "https://github.com/IndigoCarmine/moleucle_3dview_rs" }
eframe = { version = "0.35.0", default-features = false, features = ["default_fonts", "wgpu"] }
egui = "0.35.0"
egui-wgpu = "0.35.0"
lin_alg = { version = "1.4.2", features = ["computer_graphics"] }
zunda_rs = "0.5.0"
rfd = "0.17"
